### PR TITLE
Only prepare a query once per name. Use the cached id afterwards

### PR DESCRIPTION
**Pull request by drapp**
This makes it easy to lazily prepare queries, rather than trying to
prepare them once at the beginning.

### CODE REVIEW

**Comment by rpt** [comment]
Statements need to be prepared on every connection. The same query always returns the same id on every connection, so there's no point in checking if it already exists.

**Comment by drapp** [comment]
Let me explain what I'm doing and why I think this is a useful feature. I've got a bunch of functions like this:

``` erlang
store_something(Something) ->
    {ok, _} = erlcql_poolboy:p(QueryStatement, name),
    erlcql_poolboy:e(name, [Something]).
```

I'm not storing any state myself, I'm just letting each erlcql worker handle that. I only want to prepare each statement once per connection, and then use the query id from then on, but I want to make sure all workers get a query id, and if a worker gets restarted, I want to make sure it ends up doing the prepare again. This pull request would let that just work, I think, since the prepare would be a cache lookup when the worker has a prepared query, and a cassandra call when it doesn't. If there's another way to accomplish the same ends I'd be interested to hear it.

**Comment by rpt** [comment]
Right now all the clients in a pool use the same ETS table, so if a client crashes and restarts, it will do a lookup, see the name/query id is there and never prepare the statement, so it will not work. I added a test in rpt/erlcql_poolboy@92295bf987af1f69f9a7acd9b8fbce1485154cff to prove it, please run it with your version of `erlcql`.

The "proper" way to use prepared statements right now is to put them in the start opts:

``` erlang
Queries = [{name, QueryStatement}],
erlcql_poolboy:start_link(pool, [], [{prepare, Queries}]).
```

This way they will be available on all connections and redone on client restarts.

For me in most situations you know your queries upfront, so preparing queries dynamically is not a priority. I will have your suggestions in mind and try to come up with a solution that will also be easy to use with queries prepared in runtime.

**Comment by drapp** [comment]
I see, I missed that the ets was shared. In that case, your solution should work great, thanks!

**Pull request closed without merging**
