### PR TITLE
Change dependency from avtobiff/erlang-uuid to okeuday/uuid

### PR DESCRIPTION
**Pull request by inou**
solves deps conflict

### CODE REVIEW

**Comment by rpt** [comment]
@inou Why would I want to change it?

**Comment by inou** [comment]
uuid is already used in our system

**Comment by rpt** [comment]
This is a general purpose client, not a part of "our system". Is there any meaningful reason to change it?

AFAIK avtobiff's implementation was first, so you should report the conflicting names issue to okeuday.

**Comment by inou** [comment]
The reason is just conveniance, but there is no problem at all - we can always use forked repo. No worries. 
One question though - since uuid is used just in one place in code did you concider getting rid of uuid app as a dep  and either leaving it as it is (without uuid:to_string fun applied) or providing external decoder as MFA?

**Comment by rpt** [comment]
I will think about it ;) Thanks.

**Pull request closed without merging**
